/*
 this c file contains functions that are responsible for printing data to a specific file.
 */


#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include "print.h"

/// Prints the clusters to the file "clusters.txt" for k=1.
int clusters_to_file_k_is_1_c(int N)
{
    int i,j;
    FILE *f = fopen("clusters.txt", "a");
    if (f==NULL){
        PyErr_SetString(PyExc_TypeError, "clusters_to_file_k_is_1_c : could not open clusters file");
        return -1;
    }
    fprintf(f,"%d\n",1);
    for (i=0;i<2;i++){
        fprintf(f, "%d", 0);
        for ( j=1 ; j<N ; j++ ) {
            fprintf(f, ",%d", j);
        }
        if (i==0)
            fprintf(f,"\n");
    }
    fclose(f);
    return 1;
}

/// Given X - n samples from dim d generated by make_blobs and Y -
/// the integer labels for cluster membership of each sample,
/// prints X and Y to the file "data.txt".
int data_to_file_c(double **X, int *Y, int n, int d)
{
    FILE *f = fopen("data.txt", "w");
    if (f==NULL){
        PyErr_SetString(PyExc_TypeError, "data_to_file_c : could not open data file");
        return -1;
    }
    int i,j;
    for (i=0; i<n; i++){
        fprintf(f,"%.8f", X[i][0]);
        for (j=1 ; j<d ; j++){
            fprintf(f,",%.8f", X[i][j]);
        }
        fprintf(f,",%d\n", Y[i]);
    }
    fprintf(f,"\n");
    fclose(f);
    return 1;
}


